--- #YAML:1.0
name:                Audio-Ardour-Control
version:             0.10
abstract:            Automate the Ardour DAW software.
license:             ~
author:              
    - Jonathan Stowe <jns@gellyfish.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::LibLO:                    0.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
